name: Commit

on: [push]

jobs:
  test:
    name: Test on Go ${{ matrix.go }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - "ubuntu-latest"
        - "ubuntu-22.04"
        - "windows-latest"
        - "macos-latest"
        go: 
        - ">=1.22"

    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -count=1 -race -v ./...
