name: Commit

on: 
  push:
    branches: 
      - "feat/*"
      - "fix/*"
      - "ref/*"

jobs:
  test:
    name: Test on Go ${{ matrix.go }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - "ubuntu-latest"
        - "ubuntu-22.04"
        - "ubuntu-20-04"
        - "windows-latest"
        - "macos-latest"
        go:
        - "1.24.1"
        - "1.24.0"
        - "1.23"
        - "1.22"
        - "1.21"
        - "1.20"

    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@5
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -race -cover -v ./...
